version: 0.0
os: linux
files:
 - source: /index.html
    destination: /var/www/html/
    source: /userlogin.html
    destination: /var/www/html/
    source: /userreg.html
    destination: /var/www/html/
    source: /adminhome.html
    destination: /var/www/html/
    source: /adminlogin.html
    destination: /var/www/html/
    source: /contact.html
    destination: /var/www/html/
    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
